name: sherpa_onnx_dart
description: A Dart package wrapping the sherpa-onnx speech recognition library.
version: 1.0.0

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  ffi: 
  ffigen:
  fftea:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  native_assets_cli: ^0.5.0
  native_toolchain_c: ^0.4.0

ffigen:
  output: 'lib/src/sherpa_onnx_dart.g.dart'
  headers:
    entry-points:
      - 'native/include/c-api.h'
    include-directives:
      - 'native/include/c-api.h'
  ffi-native:
    assetId: package:sherpa_onnx_dart/sherpa_onnx_dart.dart

